apiVersion: v1
kind: Service
metadata:
  name: tcpdump-webhook
  namespace: default
spec:
  selector:
    app: tcpdump-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-webhook
  namespace: default
  labels:
    app: tcpdump-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpdump-webhook
  template:
    metadata:
      labels:
        app: tcpdump-webhook
    spec:
      serviceAccountName: tcpdump-webhook
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
      - name: server
        image: uzumlukek/tcpdump-webhook:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: tls
        - containerPort: 80
          name: metrics
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /etc/webhook/certs/
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: tcpdump-webhook-tls